# SPDX-FileCopyrightText: 2025 Dom Rodriguez <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: GPL-3.0-only
# This file contains installer configuration secrets
# To encrypt this file, run: sops -e -i config.yaml

zerotier-network-id: "REPLACE_WITH_YOUR_ZEROTIER_NETWORK_ID"
installer-ssh-keys:
  - "REPLACE_WITH_YOUR_SSH_PUBLIC_KEY_1"
  - "REPLACE_WITH_YOUR_SSH_PUBLIC_KEY_2"